import customtkinter as ctk
ctk.set_appearance_mode("dark")
app = ctk.CTk()
app.title("DisasterEye AI")
app.geometry("800x600")
heading = ctk.CTkLabel(app, text="DisasterEye AI - Disaster Image Analyzer", font=("Arial", 20))
heading.pack(pady=20)
upload_btn = ctk.CTkButton(app, text="Upload Image")
upload_btn.pack(pady=10)
preview_label = ctk.CTkLabel(app, text="", width=400, height=300, fg_color="gray20")
preview_label.pack(pady=10)
analyze_btn = ctk.CTkButton(app, text="Analyze", state="disabled")
analyze_btn.pack(pady=10)
app.mainloop()
